language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE palettepicker_testing;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: "bHL3rUtCgcQUr3OdULHx65ECSb+72RoUurUkI4dqPGGAxXHEFumVPtHXsCH0K26Qhxmqoxl0Rjb3Oxd8QXdNOxR9tnCtPVLLcZVsNu9vkEmTO1zA1iRfcAWIzVbRZzR34PH4ILwB+T/WN5OHJyn5YwwFNXnOLUzR8YZQyhHbuXA1VRPyG18IiWVg/7oPudUB72oRULR7PFmob+8SbriDgpIs01I4rABUlqHutKa8CgDD1D12RoXiutkrUq11OzekE2laIWYYiMbHG0/2t9esRzYfQcp6ojKy+J/Z0kYwnvQl5sPJ9V7HmnWy4g1GpGcpTm5nd0eCDDeXyGg7yerV+ksEzu5DJ/TKBor5h3Dobu8KDtBs6TH02kXqkUBlHqgLlUpXO+SCHEICFP/9NY2f7dDZMWpjufyHmNrDa7LPhaG6SZ57M6oepDF0LgAO74a8sBP6D2BXZ9WFwI9JqHY+QUqZDXV4qj3ZlN+59xD+lVqBBjCTb4MjqTVAMUdnIevQWjOO6NezXPN1B+Yn/SIUl/rHzaLP5tkI8a4ITxaMmP9lJkDqo5LyZdqMUowc7XU7s0f9KXGJvcOM3RdbwYh1jx8RCNpl1prFZr0vyxVUzRCG4YtJdvD2akIMPjI6/ApyLWBLUxLPt8cUqznZv9dI3Ul40Lm539fAzuWTOBwKmnw="