language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_testing;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VuhXUFQph2/74UUW0N+LBi33MIqbtJezigGwOaYDeC1Me4vH1zIzR+E9t5TVaBQNzo4YPZYWjjwT4M4bp9WkabJwEdpwHx79FDzw0Yl/ORGqXjL56MNW/vI5oJTBHpkzcpLYOfkSRzUZI0VT7SSLRVyGViB2y0tOTsm35T9HSNv3NTFxhnHYBm10Pt0i9BYtSOjQVMWTKdJy6jjgQPQJzyBIPXpkqMgOO3JpbFsHBbpX1EtoqN4mxY3QNvLOPwiXDV6RE6++cSsenTPju5qN4nPFfbiylYzWjcmD1CpEISCfTt+RPd83WEoNyU5JYfQLd+io+y+aLA16ti8+eEn3rKy7iRWThX6JqDiSQtPnwdQrAVQAeuPgjfWxCYlmTrjuNOUTtnwFW5vjIwCKuhyKX8OddXJKcwWNgeEuRwQlYAn0UydLCbullXR0xsj9jgAANkz5Pok8K9FMvhW4S9I85k6G07GrQSlgybTZbw4rBD65RKRWyCv/0LXkVxa7dpcQjeFfQ6u5neTDPoqJK5UXxCdCkH7yojaaQEPMjzUlLmonzZGMvWt/jhS+elDRGfehkESzE1DoYISrtzHJ/3+m6I5itLZgGMXZNqNYFm4rzdaL0Du+rKTML7XQq8jDszKi5sjVly0CGCjUdxo09qbS0D3jSzpYmqkkGKr0LUuKuiI=
  app: j-erickson-palette-picker